name: Bug report
labels: [bug]
body:
  - type: textarea
    id: what
    attributes: { label: What happened?, placeholder: Describe the issue }
    validations: { required: true }
  - type: input
    id: version
    attributes: { label: Version/tag, placeholder: v0.1.0 }
